[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cam", email = "cammclain@protonmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "robyn>=0.64.2",
    "sqlalchemy>=2.0.36",
]

[project.scripts]
core = "core:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
