version: '3.8'

services:
  backend:
    build: ../src/breachkit_core
    container_name: breachkit_backend
    ports:
      - "127.0.0.1:8003:8003"
    depends_on:
      - surrealdb
    environment:
      - DATABASE_URL=http://surrealdb:8000/rpc
    
    volumes:
      - ./tor-data:/var/lib/tor/hidden_service/


  frontend:
    build: ../src/services/frontend
    container_name: breachkit_nginx_frontend
    ports:
      - "127.0.0.1:8088:80"
    volumes:
      - ./tor-data:/var/lib/tor/hidden_service/

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9050"]
      interval: 30s
      timeout: 10s
      retries: 3

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: breachkit_surrealdb
    ports:
      - "127.0.0.1:8001:8000"
    command: start --log debug


  ollama:
    build: ../src/services/ollama
    container_name: ollama
    ports:
      - "11433:11433"
    


  redis:
    build: ../src/services/redis
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

